DELETE FROM `mysql`.`user` WHERE `User`='admin';
DELETE FROM `mysql`.`db` WHERE `User`='admin' AND `Db`='psychometry';

INSERT INTO `mysql`.`user` SET `Host`='%', `User`='admin', `Password`=PASSWORD('admin123'), `max_questions`=0, `max_updates`=0, `max_connections`=0, `max_user_connections`=0, `ssl_cipher`='', `x509_issuer`='', `x509_subject`='';
INSERT INTO `mysql`.`user` SET `Host`='localhost', `User`='admin', `Password`=PASSWORD('admin123'), `max_questions`=0, `max_updates`=0, `max_connections`=0, `max_user_connections`=0, `ssl_cipher`='', `x509_issuer`='', `x509_subject`='';
INSERT INTO `mysql`.`user` SET `Host`='::1', `User`='admin', `Password`=PASSWORD('admin123'), `max_questions`=0, `max_updates`=0, `max_connections`=0, `max_user_connections`=0, `ssl_cipher`='', `x509_issuer`='', `x509_subject`='';

INSERT IGNORE INTO `mysql`.`db` SET `Host`='%', `User`='admin', `Db`='%', `Select_priv`='Y', `Insert_priv`='N', `Update_priv`='N', `Delete_priv`='N', `Create_priv`='N', `Drop_priv`='N', `Grant_priv`='N', `References_priv`='N', `Index_priv`='N', `Alter_priv`='N', `Create_tmp_table_priv`='N', `Lock_tables_priv`='N', `Execute_priv`='N', `Create_view_priv`='N', `Show_view_priv`='N', `Create_routine_priv`='N', `Alter_routine_priv`='N', `Event_priv`='N', `Trigger_priv`='N';
INSERT IGNORE INTO `mysql`.`db` SET `Host`='%', `User`='admin', `Db`='psychometry', `Select_priv`='Y', `Insert_priv`='Y', `Update_priv`='Y', `Delete_priv`='Y', `Create_priv`='Y', `Drop_priv`='Y', `Grant_priv`='N', `References_priv`='Y', `Index_priv`='Y', `Alter_priv`='Y', `Create_tmp_table_priv`='Y', `Lock_tables_priv`='Y', `Create_view_priv`='Y', `Show_view_priv`='Y', `Create_routine_priv`='Y', `Alter_routine_priv`='Y', `Execute_priv`='Y', `Event_priv`='Y', `Trigger_priv`='Y';
INSERT IGNORE INTO `mysql`.`db` SET `Host`='::1', `User`='admin', `Db`='%', `Select_priv`='Y', `Insert_priv`='N', `Update_priv`='N', `Delete_priv`='N', `Create_priv`='N', `Drop_priv`='N', `Grant_priv`='N', `References_priv`='N', `Index_priv`='N', `Alter_priv`='N', `Create_tmp_table_priv`='N', `Lock_tables_priv`='N', `Execute_priv`='N', `Create_view_priv`='N', `Show_view_priv`='N', `Create_routine_priv`='N', `Alter_routine_priv`='N', `Event_priv`='N', `Trigger_priv`='N';
INSERT IGNORE INTO `mysql`.`db` SET `Host`='::1', `User`='admin', `Db`='psychometry', `Select_priv`='Y', `Insert_priv`='Y', `Update_priv`='Y', `Delete_priv`='Y', `Create_priv`='Y', `Drop_priv`='Y', `Grant_priv`='N', `References_priv`='Y', `Index_priv`='Y', `Alter_priv`='Y', `Create_tmp_table_priv`='Y', `Lock_tables_priv`='Y', `Create_view_priv`='Y', `Show_view_priv`='Y', `Create_routine_priv`='Y', `Alter_routine_priv`='Y', `Execute_priv`='Y', `Event_priv`='Y', `Trigger_priv`='Y';
FLUSH PRIVILEGES;